### PR TITLE
(#4) - Support Cookies

### PR DESCRIPTION
**Pull request by ddouglascarr**
Adds cookie support. You can specify the cookie on the command line with the -c or --cookie flag.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Cool, thanks!

**Comment by nolanlawson** [comment]
Wait, quick question: are there any cases where you would need cookies as opposed to HTTP authentication like `http://username:password@mysite.com`? Both Cloudant and CouchDB support either, so it feels cleaner to just support HTTP in this CLI.

**Comment by ddouglascarr** [comment]
The reason I use it is because I made a password storage system that starts a couchDB auth session and returns a cookie. I run the cli nightly, and didn't want to give the process direct access to the password.

**Comment by nolanlawson** [comment]
This sounds like a very specialized use case. I'm not really convinced that it makes sense to add it to this CLI.

Also at some point your server is sending a password to CouchDB (in order to get the cookie back), so does this really increase security any more than just sending the password directly from the CLI process? Not trying to play "gotcha," just genuinely curious here.

**Pull request closed without merging**
